name: complex

on: push

jobs:
    ubuntu:
        runs-on: ubuntu-latest
        
        steps:
          - uses: actions/checkout@v3
          - run: date
    windows:
        runs-on: windows-latest
        
        steps:
          - uses: actions/checkout@v3

          - run: date
    macos:
        runs-on: macos-latest
        
        steps:
          - uses: actions/checkout@v3

          - run: date
    depends:
        runs-on: macos-latest
        needs: [ubuntu, windows, macos]
        
        steps:
          - uses: actions/checkout@v3
         
          - run: date      
